### ISSUE TITLE
Empty sitemap / infinite loading

### ISSUE THREAD

**Issue by jpvalery** [TryGhost/gatsby-plugin-advanced-sitemap#1]
Thanks for releasing this plugin! 

Installed it on my project but I'm running into an error and I have no idea why.

I added
`    'gatsby-plugin-advanced-sitemap',`
in gatsby-config.js as specified. 

When I check https://jpvalery.photo/sitemap.xml I see a link to https://jpvalery.photo/sitemap-pages.xml but this seems to be not functioning.

Any idea of what I might have done wrong? How can I solve this? 

Thanks in advance for your help.

**Comment by AileenCGN** [comment]
@jpvalery it's almost impossible to tell what's wrong or not working without knowing more details in order to reproduce this issue. Could you share your `gatsby-config.js`? Which version of Gatsby are you on? Which sources are you using? Do you get any errors on your build?

**Comment by AileenCGN** [comment]
@jpvalery Can you tell me the outcome when you run this query

```graphql
{
  allSitePage {
    edges {
      node {
        id
        slug: path
        url: path
      }
    }
  }
  site {
    siteMetadata {
      siteUrl
    }
  }
}
```

in the GraphiQL interface when you run `gatsby develop`: http://localhost:8000/___graphql

**Comment by jpvalery** [comment]
Sorry about that and thanks for the fast reply. 

I didn't get any error on build on Netlify, the site works as expected, the only issue was the one aforementioned. 

Here's my gastby-config.js

```
const config = require('./src/utils/siteConfig')
let contentfulConfig

try {
  contentfulConfig = require('./.contentful')
} catch (e) {
  contentfulConfig = {
    production: {
      spaceId: process.env.SPACE_ID,
      accessToken: process.env.ACCESS_TOKEN,
    },
  }
} finally {
  const { spaceId, accessToken } = contentfulConfig.production
  if (!spaceId || !accessToken) {
    throw new Error('Contentful space ID and access token need to be provided.')
  }
}

module.exports = {
  siteMetadata: {
    siteUrl: config.siteUrl,
    rssMetadata: {
      site_url: config.siteUrl,
      feed_url: `${config.siteUrl}/rss.xml`,
      title: config.siteTitle,
      description: config.siteDescription,
      image_url: `${config.siteUrl}${config.siteLogo}`,
      author: config.author,
      copyright: config.copyright,
    },
  },
  plugins: [
    {
     resolve: 'gatsby-plugin-fathom',
     options: {
       // your Fathom server URL
       trackingUrl: 'jpvalery.usesfathom.com',
       // unique site id (optional, required for Fathom v1.1.0+)
       siteId: 'XXXXXXX'
     },
   },
    {
      resolve: 'gatsby-plugin-canonical-urls',
      options: {
        siteUrl: config.siteUrl,
      },
    },
    {
      resolve: `gatsby-plugin-emotion`,
      options: {
        // Accepts all options defined by `babel-plugin-emotion` plugin.
      },
    },
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-prismjs`,
            options: {
              classPrefix: 'language-',
              showLineNumbers: true,
            },
          },
          {
            resolve: `gatsby-remark-images-contentful`,
            options: {
              maxWidth: 650,
              backgroundColor: 'white',
              linkImagesToOriginal: false,
            },
          },
        ],
      },
    },
    {
      resolve: 'gatsby-source-contentful',
      options:
        process.env.NODE_ENV === 'development'
          ? contentfulConfig.development
          : contentfulConfig.production,
    },
    'gatsby-plugin-catch-links',
    'gatsby-plugin-sitemap',
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: config.siteTitle,
        short_name: config.shortTitle,
        description: config.siteDescription,
        start_url: '/',
        background_color: config.backgroundColor,
        theme_color: config.themeColor,
        display: 'fullscreen',
        icon: `static${config.siteLogo}`,
      },
    },
    'gatsby-plugin-offline',
    {
      resolve: 'gatsby-plugin-feed',
      options: {
        setup(ref) {
          const ret = ref.query.site.siteMetadata.rssMetadata
          ret.allMarkdownRemark = ref.query.allMarkdownRemark
          ret.generator = 'Jp Valery'
          return ret
        },
        query: `
    {
      site {
        siteMetadata {
          rssMetadata {
            site_url
            feed_url
            title
            description
            image_url
            author
            copyright
          }
        }
      }
    }
  `,
        feeds: [
          {
            serialize(ctx) {
              const rssMetadata = ctx.query.site.siteMetadata.rssMetadata
              return ctx.query.allContentfulPost.edges.map(edge => ({
                date: edge.node.publishDate,
                title: edge.node.title,
                description: edge.node.body.childMarkdownRemark.excerpt,

                url: rssMetadata.site_url + '/' + edge.node.slug,
                guid: rssMetadata.site_url + '/' + edge.node.slug,
                custom_elements: [
                  {
                    'content:encoded': edge.node.body.childMarkdownRemark.html,
                  },
                ],
              }))
            },
            query: `
              {
            allContentfulPost(limit: 1000, sort: {fields: [publishDate], order: DESC}) {
               edges {
                 node {
                   title
                   slug
                   publishDate(formatString: "MMMM DD, YYYY")
                   body {
                     childMarkdownRemark {
                       html
                       excerpt(pruneLength: 80)
                     }
                   }
                 }
               }
             }
           }
      `,
            output: '/rss.xml',
          },
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-nprogress',
      options: {
        color: config.themeColor,
      },
    },
    'gatsby-plugin-netlify',
    'gatsby-plugin-advanced-sitemap',
  ],
}

```

Running the query, I get: 
```
{
  "errors": [
    {
      "message": "Syntax Error: Unexpected Name \"allSitePage\"",
      "locations": [
        {
          "line": 32,
          "column": 3
        }
      ]
    }
  ]
}
```

Last but not least, here's the gastby info:

> 
>  System:
>     OS: macOS 10.14.3
>     CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 10.15.0 - /usr/local/bin/node
>     Yarn: 1.13.0 - /usr/local/bin/yarn
>     npm: 6.9.0 - /usr/local/bin/npm
>   Languages:
>     Python: 2.7.10 - /usr/bin/python
>   Browsers:
>     Firefox: 65.0.1
>     Safari: 12.0.3
>   npmPackages:
>     gatsby: ^2.0.91 => 2.1.30 
>     gatsby-image: ^2.0.0-rc.4 => 2.0.32 
>     gatsby-plugin-advanced-sitemap: ^1.0.3 => 1.0.3 
>     gatsby-plugin-canonical-urls: ^2.0.0-rc.2 => 2.0.12 
>     gatsby-plugin-catch-links: ^2.0.2 => 2.0.13 
>     gatsby-plugin-emotion: ^2.0.5 => 2.0.7 
>     gatsby-plugin-fathom: ^1.0.4 => 1.0.4 
>     gatsby-plugin-feed: 2.0.9 => 2.0.9 
>     gatsby-plugin-manifest: 2.0.7 => 2.0.7 
>     gatsby-plugin-netlify: ^2.0.6 => 2.0.12 
>     gatsby-plugin-nprogress: 2.0.6 => 2.0.6 
>     gatsby-plugin-offline: ^2.0.0-rc.4 => 2.0.25 
>     gatsby-plugin-react-helmet: 3.0.1 => 3.0.1 
>     gatsby-plugin-sitemap: ^2.0.0-rc.2 => 2.0.8 
>     gatsby-plugin-styled-components: ^3.0.0-rc.5 => 3.0.7 
>     gatsby-plugin-typography: 2.2.1 => 2.2.1 
>     gatsby-remark-images-contentful: ^2.0.0-rc.6 => 2.0.9 
>     gatsby-remark-prismjs: 3.0.3 => 3.0.3 
>     gatsby-source-contentful: ^2.0.1-rc.4 => 2.0.37 
>     gatsby-source-filesystem: ^2.0.23 => 2.0.24 
>     gatsby-transformer-remark: ^2.1.0 => 2.3.2 
>   npmGlobalPackages:
>     gatsby-cli: 2.4.8

Is there anything else I can provide to help?

Thanks a lot again for your help

**Comment by AileenCGN** [comment]
Hmm... I tried to reproduce this, using the Gatsby Contentful Netlify, which is the one yours is based on it seems, but it works fine for me.

What I can see is, that you're still using the `gatsby-plugin-sitemap`, which you should remove in favour of the advanced sitemap. But even when I used both plugins, it still worked fine for me:

![image](https://user-images.githubusercontent.com/8037602/54328657-b6816100-4649-11e9-8000-7686787b75f3.png)

The important thing is, that the plugin (even the default plugin that you were using before) is using the `allSitePage` query. And Gatsby creates this by default. Did `gatsby-plugin-sitemap` work correctly for you?

**Comment by jpvalery** [comment]
Honestly I didn’t even check it. I just follow closely what you folks are brewing at Ghost and wanted to use that plugin :)

I could try removing advanced-sitemap and see if it works - or would it be easier to give you access to the private repo?

**Comment by AileenCGN** [comment]
I'm actually really curious to see why it doesn't work in your case. As the plugin is still pretty fresh we weren't able to receive a lot of feedback yet and naturally we only tested with common and known situations.

If you'd like you can send me an invite to your repo, so I could have a look myself (you can kick me out later again). Or try debugging yourself. Whatever you prefer 😊

**Comment by jpvalery** [comment]
Just sent you an invite! :) Really appreciate all the help/advices/friendliness :pray:

**Comment by AileenCGN** [comment]
Well, I cloned your repo, installed the dependencies, updated the `siteUrl` in `siteConfig` for testing purposes to `http://localhost:9000` and guess what:

![image](https://user-images.githubusercontent.com/8037602/54330552-32cb7280-4651-11e9-9156-0db6937a9c37.png)

The query works also fine for me locally. I would maybe try to clear cache everywhere (on Netflify trigger the build with clearing the cache), delete your browser cache and the service worker and try again. I honestly don't know what else could be causing this issue 🤔

**Comment by jpvalery** [comment]
🤔 indeed! I got in touch with Netlify to ask them to clear the cache and redeploy. I'll let you know if that changes anything.

Might take 24-48h to hear back and will report back as soon as I can test.

**Comment by jpvalery** [comment]
So I finally managed to rebuild without cache. And unfortunately, I'm still getting the same error...

Nothing seems to be going wrong during the build from what I can read in the logs.  

I've quickly tried locally and sitemap-pages.xml doesn't have any formatting but it works and the content seems to be there...
<img width="1933" alt="image" src="https://user-images.githubusercontent.com/4112343/54503934-cc23ae80-4907-11e9-882a-0cf01be4802e.png">

Any idea of what I could be missing or doing wrong?

**Comment by AileenCGN** [comment]
When you're testing it locally, you will need to temporary change your `siteUrl` in `siteConfig.js` to `http://localhost:9000`, because otherwise the xsl stylesheet reference doesn't work.

**Comment by jpvalery** [comment]
I actually did `siteUrl: 'localhost:9000', `
Switching to `http://localhost:9000` indeed put back the styling.

Could it be that in my original file, the url is `siteUrl: 'https://jpvalery.photo', ` and that the https messes things up? (Sorry if it's a stupid question)

**Comment by AileenCGN** [comment]
> Could it be that in my original file, the url is siteUrl: 'https://jpvalery.photo', and that the https messes things up?

It _shouldn't_. Something weird must happen within Netlify, or maybe even the offline-plugin, seeing that it works fine locally. Are you using any other build variables within Netlify?

I don't know what it could be other than that 🤔

**Comment by jpvalery** [comment]
Hey,

Here’s the reply from Netlify:

Hello JP,

I've no idea what is causing your sitemap to not work, unfortunately, since your build is not failing and it doesn't seem likely to be any error messages. The easiest way to debug your build in our environment is to pull down the docker container that we use as a build image and use it interactively:

docker pull netlify/build
git clone https://github.com/netlify/build-image
cd build-image
./test-tools/start-image.sh /path/to/your/checked/out/repository
build whatever_your_build_command_is
If you want some more context on why I suggest this, our build process is described in detail here:

https://www.netlify.com/blog/2016/10/18/how-our-build-bots-build-sites/

--
	Dennis from Netlify

I’ll look into the offline plugin and the build variables but AFAIK nothing special here.

**Comment by jpvalery** [comment]
Hey,

Here’s the reply from Netlify:

> 
> Hello JP,
> 
> I've no idea what is causing your sitemap to not work, unfortunately, since your build is not failing and it doesn't seem likely to be any error messages. The easiest way to debug your build in our environment is to pull down the docker container that we use as a build image and use it interactively:
> 
> docker pull netlify/build
> git clone https://github.com/netlify/build-image
> cd build-image
> ./test-tools/start-image.sh /path/to/your/checked/out/repository
> build whatever_your_build_command_is
> If you want some more context on why I suggest this, our build process is described in detail here:
> 
> https://www.netlify.com/blog/2016/10/18/how-our-build-bots-build-sites/
> 
> 	Dennis from Netlify

I've made a branch where I removed the offline plugin and the sitemap plugin, updated the siteURL config. And updated yarn.lock. 

Currently testing and will report back as soon as I have some results

**Comment by jpvalery** [comment]
Well that didn't work. The site deploys but the error is still there. 

I tried downloading the zip of the deploy, and the sitemap-pages.xml file is empty. 

Here's the build log from netlify: 

> 9:14:29 AM: Build ready to start
> 9:14:31 AM: build-image version: bc22f7ea2f97324f8ca25c36353605ddd91e092d
> 9:14:31 AM: build-image tag: v2.6.15
> 9:14:31 AM: buildbot version: 18b7c3e30760449e17ed022a7e9b9d68eac6d129
> 9:14:31 AM: Fetching cached dependencies
> 9:14:31 AM: Starting to download cache of 267.5MB
> 9:14:33 AM: Finished downloading cache in 1.685162337s
> 9:14:33 AM: Starting to extract cache
> 9:14:41 AM: Finished extracting cache in 8.654983945s
> 9:14:42 AM: Finished fetching cache in 10.531414414s
> 9:14:42 AM: Starting to prepare the repo for build
> 9:14:42 AM: Preparing Git Reference refs/heads/sitemap-fixing
> 9:14:43 AM: Starting build script
> 9:14:43 AM: Installing dependencies
> 9:14:44 AM: Started restoring cached node version
> 9:14:45 AM: Finished restoring cached node version
> 9:14:45 AM: Attempting node version 'v10.13.0' from .nvmrc
> 9:14:45 AM: v10.13.0 is already installed.
> 9:14:46 AM: Now using node v10.13.0 (npm v6.4.1)
> 9:14:46 AM: Attempting ruby version 2.3.6, read from environment
> 9:14:48 AM: Using ruby version 2.3.6
> 9:14:48 AM: Using PHP version 5.6
> 9:14:48 AM: Started restoring cached node modules
> 9:14:48 AM: Finished restoring cached node modules
> 9:14:48 AM: Started restoring cached yarn cache
> 9:14:48 AM: Finished restoring cached yarn cache
> 9:14:49 AM: Installing NPM modules using Yarn version 1.3.2
> 9:14:50 AM: yarn install v1.3.2
> 9:14:50 AM: (node:1199) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> 9:14:50 AM: [1/4] Resolving packages...
> 9:14:51 AM: success Already up-to-date.
> 9:14:51 AM: Done in 1.07s.
> 9:14:51 AM: NPM modules installed using Yarn
> 9:14:51 AM: (node:1220) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> 9:14:51 AM: Started restoring cached go cache
> 9:14:53 AM: Finished restoring cached go cache
> 9:14:53 AM: Installing Go version 1.10
> 9:14:53 AM: unset GOOS;
> 9:14:53 AM: unset GOARCH;
> 9:14:53 AM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
> 9:14:53 AM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
> 9:14:53 AM: go version >&2;
> 9:14:53 AM: export GIMME_ENV='/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env';
> 9:14:53 AM: go version go1.10 linux/amd64
> 9:14:53 AM: Installing missing commands
> 9:14:53 AM: Verify run directory
> 9:14:53 AM: Executing user command: gatsby build
> 9:14:56 AM: success open and validate gatsby-configs — 0.012 s
> 9:14:57 AM: success load plugins — 0.471 s
> 9:14:57 AM: success onPreInit — 0.686 s
> 9:14:57 AM: success delete html and css files from previous builds — 0.009 s
> 9:14:57 AM: success initialize cache — 0.007 s
> 9:14:57 AM: success copy gatsby files — 0.019 s
> 9:14:57 AM: success onPreBootstrap — 0.010 s
> 9:14:57 AM: Starting to fetch data from Contentful
> 9:14:57 AM: Fetching default locale
> 9:14:57 AM: default locale is : en-US
> 9:14:58 AM: contentTypes fetched 8
> 9:14:58 AM: Updated entries  28
> 9:14:58 AM: Deleted entries  0
> 9:14:58 AM: Updated assets  210
> 9:14:58 AM: Deleted assets  0
> 9:14:58 AM: Fetch Contentful data: 418.087ms
> 9:14:58 AM: success source and transform nodes — 0.796 s
> 9:14:59 AM: success building schema — 0.660 s
> 9:14:59 AM: success createPages — 0.099 s
> 9:14:59 AM: success createPagesStatefully — 0.040 s
> 9:14:59 AM: success onPreExtractQueries — 0.005 s
> 9:14:59 AM: success update schema — 0.325 s
> 9:15:00 AM: success extract queries from components — 0.346 s
> 9:15:01 AM: success run graphql queries — 1.767 s — 22/22 12.63 queries/second
> 9:15:01 AM: success write out page data — 0.005 s
> 9:15:01 AM: success write out redirect data — 0.001 s
> 9:15:02 AM: done generating icons for manifest
> 9:15:02 AM: success onPostBootstrap — 0.298 s
> 9:15:02 AM: info bootstrap finished - 8.271 s
> 9:15:17 AM: success Building production JavaScript and CSS bundles — 15.236 s
> 9:15:20 AM: success Building static HTML for pages — 2.909 s — 22/22 29.51 pages/second
> 9:15:20 AM: info Done building in 26.521 sec
> 9:15:20 AM: Caching artifacts
> 9:15:20 AM: Started saving node modules
> 9:15:20 AM: Finished saving node modules
> 9:15:20 AM: Started saving yarn cache
> 9:15:20 AM: Finished saving yarn cache
> 9:15:20 AM: Started saving pip cache
> 9:15:20 AM: Finished saving pip cache
> 9:15:20 AM: Started saving emacs cask dependencies
> 9:15:20 AM: Finished saving emacs cask dependencies
> 9:15:20 AM: Started saving maven dependencies
> 9:15:20 AM: Finished saving maven dependencies
> 9:15:20 AM: Started saving boot dependencies
> 9:15:20 AM: Finished saving boot dependencies
> 9:15:20 AM: Started saving go dependencies
> 9:15:22 AM: Finished saving go dependencies
> 9:15:22 AM: Build script success
> 9:15:22 AM: Starting to deploy site from 'public/'
> 9:15:23 AM: 42 new files to upload
> 9:15:23 AM: 0 new functions to upload
> 9:15:26 AM: Starting post processing
> 9:15:26 AM: Minifying bundle
> 9:15:29 AM: Minifying bundle
> 9:15:32 AM: Minifying bundle
> 9:15:38 AM: Minifying bundle
> 9:15:41 AM: Minifying bundle
> 9:15:43 AM: Minifying bundle
> 9:15:46 AM: Minifying bundle
> 9:15:50 AM: Minifying bundle
> 9:15:56 AM: Post processing done
> 9:15:56 AM: Site is live
> 9:16:10 AM: Finished processing build request in 1m39.062550344s
> 9:16:10 AM: Shutting down logging, 0 messages pending

So even with yarn.lock updated and build deploying correctly, this sitemap-pages.xml remains empty...

**Comment by AileenCGN** [comment]
The only difference I can see from the setups we're using and yours, is the "Asset optimization", which is completely disabled in our setup. I wonder if that has anything to do with it...

**Comment by jpvalery** [comment]
Trying with the JS asset optimization options deactivated + rebuilding with cache cleared.

**Comment by jpvalery** [comment]
Doesnt work either. Same issue :(

**Comment by jpvalery** [comment]
I've tried to change the build command and it was a bad idea - the deploy gets stuck and Netlify doesn't offer any way to abort a build. Waiting for it to auto-abort or them to kill it. 
Once it's over, I'll give disabling pretty URLs a try. 

As for Netlify, the only reply I got from them was:

> Hello JP,
> I've no idea what is causing your sitemap to not work, unfortunately, since your build is not failing and it doesn't seem likely to be any error messages. 
> The easiest way to debug your build in our environment is to pull down the docker container that we use as a build image and use it interactively:
> ```
> docker pull netlify/build
> git clone https://github.com/netlify/build-image
> cd build-image
> ./test-tools/start-image.sh /path/to/your/checked/out/repository
> ```
> build whatever_your_build_command_is
> 
> If you want some more context on why I suggest this, our build process is described in detail here:https://www.netlify.com/blog/2016/10/18/how-our-build-bots-build-sites/
>  --

So I'm now trying their suggestion as well. Even though I have 0 docker knowledge and I don't see how I'm supposed to magically figure out what's going wrong on their end 🔮

**Comment by AileenCGN** [comment]
> Could it be that it's the pretty URLs that is messing with it?

This could be a reason as well.

> Could it be that the build command needs to be gatsby build && gatsby serve?

No, it should just work with the standard `gatsby build`

> Could it be that it's the default settings that are not working in that case - i.e. should we try to set up options for the plugin?

The plugin _should_ work as default, but you could also try a Contentful, customised setup. I used it with a Contentful source like this:

```
    {
      resolve: `gatsby-plugin-advanced-sitemap`,
      options: {
        query: `
          {
            allContentfulArticle(sort: {order: ASC, fields: publishedAt}, filter: {node_locale: {eq: "en-US"}}) {
              edges {
                  node {
                    id
                    slug
                    published_at: publishedAt
                    updated_at: updatedAt
                    created_at: createdAt
                    featureImage {
                      title
                    }
                  }
              }
            }
            allContentfulTag(sort: {order: ASC, fields: createdAt}, filter: {node_locale: {eq: "en-US"}}) {
              edges {
                  node {
                      id
                      slug
                      updated_at: updatedAt
                      created_at: createdAt
                  }
              }
            }
            allContentfulCourse(sort: {order: ASC, fields: createdAt}, filter: {node_locale: {eq: "en-US"}}) {
              edges {
                  node {
                      id
                      slug
                      updated_at: updatedAt
                      created_at: createdAt
                  }
              }
            }
        }`,
        mapping: {
          allContentfulArticle: {
            sitemap: `posts`,
          },
          allContentfulTag: {
            sitemap: `tags`,
          },
          allContentfulCourse: {
            sitemap: `pages`,
          },
        },
      }
    },
```

You would need to adjust the fieldnames and make you that your content includes the minimum required fields `id` and `slug`.

But before you take that step, you should try again using the [`gatsby-plugin-sitemap`](https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/) again, because this is using the same technique (`allSitePages`) like this plugin does, when nothing is specified. If this plugin doesn't result in showing listing all your pages, then it's not caused by this plugin specifically. If it does work, then we'll need to dig further and find out what's causing the plugin to fail for you. Really sorry that you're functioning here as a guinea pig 😔

**Comment by jpvalery** [comment]
Hey!

No worries :) Happy to help and appreciating your patience and everything :100: 

I've tried the `disabling pretty URLs` and it didn't change anything. I'll give a try to removing `advanced-sitemap` and reinstalling `sitemap` tomorrow evening or tuesday's and see how it goes.
_I'd be tempted to say it will work since https://iammatthias.com/sitemap.xml works and my portfolio is forked from his_

I've also asked for more guidance from Netlify (even though I've 0 expectations on their reply seen how they replied in the last couple of weeks) and highlighted the fact that it doesn't make the build fail and it works perfectly locally.

**Comment by jpvalery** [comment]
https://jpvalery.photo/sitemap.xml it does work indeed :( 
<img width="2248" alt="image" src="https://user-images.githubusercontent.com/4112343/54893401-005d1900-4e8c-11e9-92b0-29d2169a63af.png">

**Comment by jpvalery** [comment]
So `gatsby-plugin-sitemap`works. 

I've tried 
```
npm uninstall gatsby-plugin-sitemap
npm install gatsby-plugin-advance-sitemap
```
followed by updating gatsby-config.js. And unfortunately the error/issue/bug is still happening. 
Even if I try [deploying with a cleared cache](https://5c984b047d43a0bb588a9f45--jpvalery-portfolio.netlify.com/).

In the mean time, I've reverted to my deploy with `gatsby-plugin-sitemap`. 

If that can be of any help, I've also opened my repo to the public today - if you need to toy around with it, you can get it at https://github.com/jpvalery/portfolio. 

I can send you the Contentful Space_ID and Access_Token if you haven't kept a copy of the repo when it was private and included .contentful.json

Let me know if there's anything else I can help with on my side. Gotta confess that I feel a bit helpless at this point :(

**Comment by AileenCGN** [comment]
Ok. I copied your repo over (still had the credentials) and deployed to a test Netlify site: https://xenodochial-borg-469f65.netlify.com

Same issue here!! Will try the docker build and see if I can get to the cause of it.

**Comment by AileenCGN** [comment]
I played around with it using Docker, but unfortunately could not find the reason why it's not working like it is locally. I can see, that the `sitemap-pages.xml` file gets generated, but it's empty. Somewhere on the way, it goes wrong. 

I tried the same for the `gatsby-starter-gcn`, which leads to the same problem. Works fine locally, but not with Docker.

I will reach out to Netlify to see if they can figure it out (they should!!), as it doesn't seem to be caused by the plugin itself somehow.

I will report here later. Until then, when running into this issue, please use the standard sitemap plugin.

**Comment by jpvalery** [comment]
Thank you so much for all these efforts.

If you have a support ticket number, please send it my way so I can reference it in mine.

Let me know if there’s anything else I can do in the mean time.

**Comment by AileenCGN** [comment]
Finally found the fix for it! Please update to 1.0.4! It should work now _finally_!!

**Comment by jpvalery** [comment]
IT WORKSSSSSSSSS https://jpvalery.photo/sitemap-pages.xml

🙌 🙌 🙌 🙌 🙌 🙌 🙌 🙌 🙌 🙌

**Comment by jpvalery** [comment]
Thank you soooooo much AileenCGN. I really really appreciated all your help and dedication 💯 

So thrilled to be rocking that Advanced Sitemap 💪

**Comment by AileenCGN** [comment]
You're very welcome! Thank you for helping so much here so we were able to find it!!
