### ISSUE TITLE
Contentful last update is wrong

### ISSUE THREAD

**Issue by devquestionz** [TryGhost/gatsby-plugin-advanced-sitemap#111]
I use this for contentful posts

```
allContentfulPost {
            edges {
              node {
                id
                slug
                updatedAt
              }
            }
          }
```

but Last Modified column always shows the wrong date (the build date) and not when the post was updated, is there a fix for this?

**Comment by aileen** [comment]
@devquestionz the plugin is expecting the property written like this: `updated_at`.

If you go ahead and change your query to:

```
allContentfulPost {
            edges {
              node {
                id
                slug
                updated_at: updatedAt
              }
            }
          }
```

it should work fine.
