### ISSUE TITLE
Error when running gatsby build with --prefix-paths

### ISSUE THREAD

**Issue by bryanberger** [TryGhost/gatsby-plugin-advanced-sitemap#13]
### Issue Summary

Trying to use this plugin and deploy to Github Pages (using gh-pages)

**Errors**
```
[Error: ENOENT: no such file or directory, open 'public/website-gatsby/sitemap.xml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/website-gatsby/sitemap.xml'
}

[Error: ENOENT: no such file or directory, open 'public/website-gatsby/sitemap-pages.xml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/website-gatsby/sitemap-pages.xml'
}
```

### To Reproduce

1. add a `pathPrefix` key/value to gatsby-config.js
2. `gatsby build --prefix-paths`

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Gatsby Version: 2.10.0
* Node Version: 12.10.0
* OS: Mac OSX Mojave

**Comment by jbuffin** [comment]
I'm having the same issue

**Comment by dimileeh** [comment]
I'm a novice in nodejs, so bear with me.
I also get this error. When I run `gatsby build --prefix-paths`, right when it starts creating HTML files, I run `mkdir public/<PREFIX_PATH>` and that's it, no errors :)

So, there are two ways to fix this issue.

1. Figure out why yarn (or npm) doesn't create the prefix-path folder in `public` for the given sitemap.xml automatically.
2. Make the sitemap ignore the prefix-path folder for the ouput of sitemap files, but leave the prefix-path in the `src` attribute of a given sitemap.
3. Give user a choice in the config on which option to choose.

The easiest would be to implement the first option and then let the user put sitemap files where appropriate through the `postbuild` config.

**Comment by dimileeh** [comment]
For now, I've selected the second option and simply removed `pathPrefix` from `indexSitemapFile` and `resourcesSitemapFile` in the `src/gatsby-node.js` file and re-added the module through `yarn add`. And it all works.

It's a shame I'm not that experienced in nodejs to contribute with the third option :(

**Comment by alexthewilde** [comment]
@dimileeh your quick fix works.

What I don't understand: why is `pathPrefix` being used here in the first place?
https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/9fb99e965fa961d93df58e2072fd72301d0e86f3/src/gatsby-node.js#L238

**Comment by MansoorMajeed** [comment]
Since I didn't need the advanced features, I ended up using the basic sitemap plugin https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/ which works fine

**Comment by srivastavarnav** [comment]
any update on this bug?

**Comment by Kumail786** [comment]
Any update on this ? facing same issue while using **gatsby-plugin-advanced-sitemap**

**Comment by yogeshkotadiya** [comment]
I've not tested fully but hopefully, this should solve issue #126

**Comment by generalpiston** [comment]
@yogeshkotadiya not entirely. It still doesn't generate sitemap-(part).xml because the nested directory doesn't exist. You might need to make any parent directories if they don't exist.

**Comment by generalpiston** [comment]
@yogeshkotadiya another problem is the relative location of `sitemap.xsl`. The sitemap files are prefixed with `pathPrefix`, but the `sitemap.xsl` is not.

**Comment by anicioalexandre** [comment]
I'm still getting this "file or directory not found" using `gatsby-plugin-advanced-sitemap` with `pathPrefix` :(

**Comment by generalpiston** [comment]
@yogeshkotadiya the offending line for `sitemap.xsl` is here: https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/95276f9c5db8d308e2277b21992baa529d11667e/src/utils.js#L13.

```
export const sitemapsUtils = {
    getDeclarations: function () {
        return `<?xml version="1.0" encoding="UTF-8"?>` +
            `<?xml-stylesheet type="text/xsl" href="sitemap.xsl"?>`;
    }
};
```

Basically, if sitemaps are generated under `pathPrefix`, then the xsl needs to be in the same directory or referenced to correctly.

Why not move it under `pathPrefix`?

**Comment by mrseanbaines** [comment]
I am facing the same issue when using `assetPrefix` since `sitemap.xsl` doesn't get prefixed but the other files do.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24367010/142640622-88424e9a-2cab-4f3c-89e8-2b27b03a4ce4.png">

Would be nice if there was an option to exclude styling altogether, then I could at least get around the issue. Although should sitemaps get prefixed anyway? I guess you'd always/usually want it at the root, e.g. example.com/sitemap.xml
