### ISSUE TITLE
Their should be handle if node.slug is undefined or null

### ISSUE THREAD

**Issue by ghanshyammac** [TryGhost/gatsby-plugin-advanced-sitemap#19]
Welcome to the Gatsby Plugin Advanced Sitemap GitHub repo! 👋🎉

We use GitHub only for bug reports 🐛

Anything else should be posted to https://forum.ghost.org 👫

For questions related to the usage of Gatsby or GraphQL, please check out their docs at https://www.gatsbyjs.org/ and https://graphql.org/

🚨For support, help & questions use https://forum.ghost.org/c/help
💡For feature requests & ideas you can post and vote on https://forum.ghost.org/c/Ideas

If your issue is with Gatsby.js itself, please report it at the Gatsby repo ➡️ https://github.com/gatsbyjs/gatsby/issues/new.

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
const slug = (source === `allMarkdownRemark` || source === `allMdx`) ? node.fields.slug.replace(/^\/|\/$/, ``) : node.slug.replace(/^\/|\/$/, ``)

In gatsby-node.js script at line number 167 their should be handle before  replace to avoid error while generating sitemap.xml

### To Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Gatsby Version:
* Node Version:
* OS:
* gatsby-config.js:

**Comment by AileenCGN** [comment]
`node.slug` is a required field, so the handle shouldn't be necessary. BUT there should be test for the existence of the field and a hard error if it's not missing.
