### ISSUE TITLE
sitemap-pages.xml is missing all pages except root

### ISSUE THREAD

**Issue by styxlab** [TryGhost/gatsby-plugin-advanced-sitemap#20]
# Description
When you inspect the page links, e.g. in the starter demo under https://gatsby.ghost.org/sitemap-pages.xml only the root link is listed but all links to pages are missing (e.g. about, rss). Compare that to the standard demo at https://demo.ghost.io/sitemap-pages.xml where those pages are listed.

# Details
I checked in the `grapghql` explorer that the pages are present under the expected path, so I suspect the fix must be made in this repo.

# Expectation
All pages of a site should be listed under sitemap-pages.xml which is important for SEO.

**Comment by kevinansfield** [comment]
@styxlab the about page is listed here https://gatsby.ghost.org/sitemap-posts.xml

**Comment by styxlab** [comment]
Okay, this is correct if the about page is a "post". I checked with an about page that is a "page" and it is not shown under sitemap-pages.xml as I would expect.

**Comment by AileenCGN** [comment]
The about page is in fact a post, not a page. Closing this as it's not an issue.
