### ISSUE TITLE
sitemap-pages.xml does not list pages of type page

### ISSUE THREAD

**Issue by styxlab** [TryGhost/gatsby-plugin-advanced-sitemap#21]
# Description

When you add a page to your blog post and source them in with gatsby-starter-ghost, those pages shoud be listed under sitemap-pages.xml. Currently, they are not shown.

# Steps to reproduce

1. `ghost install local` to get a fresh ghost installation
2. add a custom integration to generate a ContentAPI key
3. Add a **page** (e.g. /test-page/)  in ghost admin with some dummy text
4. link that page (e.g. /test-page/)  to the navigation bar.
5. clone `gatsby-starter-ghost` and change `.ghost.json` to include the keys from step 2.
6. `yarn; gatsby build; gatsby serve`
7. Observe that the added page in 3. does not show under sitemap-pages.xml 

# Expectation

All pages of a site should be listed under sitemap-pages.xml which is important for SEO.

**Comment by aileen** [comment]
Hey @styxlab 

I'm not able to reproduce this. Just added a page and ran `gatsby build && gatsby serve` and the page is perfectly shown with the current configuration of the `gatsby-starter-ghost`

<img width="855" alt="image" src="https://user-images.githubusercontent.com/8037602/93161037-ccec0980-f765-11ea-89b3-92f7b65b3bc5.png">

*_note_: the page is now deleted again in production, so you won't see it on the live page.

fyi, this is the current configuration as used in the Ghost starter theme:

```
{
    resolve: `gatsby-plugin-advanced-sitemap`,
    options: {
        query: `
        {
            allGhostPost(filter: {slug: {ne: "data-schema"}}) {
                edges {
                    node {
                        id
                        slug
                        updated_at
                        created_at
                        feature_image
                    }
                }
            }
            allGhostPage(filter: {slug: {ne: "data-schema"}}) {
                edges {
                    node {
                        id
                        slug
                        updated_at
                        created_at
                        feature_image
                    }
                }
            }
            allGhostTag(filter: {slug: {ne: "data-schema"}}) {
                edges {
                    node {
                        id
                        slug
                        feature_image
                    }
                }
            }
            allGhostAuthor(filter: {slug: {ne: "data-schema"}}) {
                edges {
                    node {
                        id
                        slug
                        profile_image
                    }
                }
            }
        }`,
        mapping: {
            allGhostPost: {
                sitemap: `posts`,
            },
            allGhostTag: {
                sitemap: `tags`,
            },
            allGhostAuthor: {
                sitemap: `authors`,
            },
            allGhostPage: {
                sitemap: `pages`,
            },
        },
        exclude: [
            `/dev-404-page`,
            `/404`,
            `/404.html`,
            `/offline-plugin-app-shell-fallback`,
            `/data-schema`,
        ],
        createLinkInHead: true,
        addUncaughtPages: true,
    },
},

```
