### ISSUE TITLE
Google can't parse this sitemap

### ISSUE THREAD

**Issue by joe-safegraph** [TryGhost/gatsby-plugin-advanced-sitemap#220]
### Issue Summary

I was a bit concerned that if this sitemap was being rendered as a pure HTML file and not as an XML file, Google wouldn't be able to parse it. So I tested this out with Google Search Console, and they can't parse it. I don't see any indication of Google support HTML parsing for sitemaps either.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/93544865/162545908-fd12abcf-4fcb-4429-8370-2df106158ed2.png">

Just to make sure, when I visit my sites `/sitemap.xml`, it clearly shows the correct page.

Is this purposefully not supported? If so, why is the default `sitemap.xml`?

**Comment by Willis0826** [comment]
Hey, the `sitemap.xml` worked perfectly with google in my side.
