### ISSUE TITLE
An option to disable description

### ISSUE THREAD

**Issue by thomkrupa** [TryGhost/gatsby-plugin-advanced-sitemap#5]
Hey,

is there an option to remove/disable the description from generated sitemaps?
"Advanced Sitemap for search engine consumption, by Ghost."

**Comment by daviddarnes** [comment]
Hey there, looks like the sitemap file is a template that's pulled in from here https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/blob/master/static/sitemap.xsl
I guess if you can access the template via `gatsby-node.js` you could remove the element from the generated page?

**Comment by AileenCGN** [comment]
Hi @thomkrupa 

Thanks for the idea!

We only keep Github issues open for bugs and in-progress feature work. Please check out [our forum](https://forum.ghost.org) to see if your suggested idea already exists, so you can upvote it, or post this idea in the features section for other users to see and upvote.

**Comment by ciokan** [comment]
The right answer is: **no there isn't** and they are not interested in making it happen (see https://github.com/TryGhost/gatsby-plugin-advanced-sitemap/pull/158). 

This plugin is nothing but a funnel to either:

- drive traffic to their forum, homepage
- get them rich SEO backlinks
