### ISSUE TITLE
siteUrl issues in review env's etc.

### ISSUE THREAD

**Issue by karolis-sh** [TryGhost/gatsby-plugin-advanced-sitemap#7]
### Issue Summary

If advanced sitemap isn't deployed, the sitemap won't because of 404d `/sitemap.xsl`. I manually tried to edit xml file and make url relative rather than absolute (`<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>`). Maybe this approach would be valid?

### To Reproduce

1. `gatsby build`
2. `gatsby serve`
3. Go to `/sitemap.xml`
4. `/sitemap.xsl` will fail to load if it is not on production server

### Technical details:

* Gatsby Version: `2.8.2`
* gatsby-config.js: default `'gatsby-plugin-advanced-sitemap'`

**Comment by AileenCGN** [comment]
Sounds like a good idea to make it relative! The other option is to change the `siteUrl` in your config to be `http://localhost:9000`.
