### ISSUE TITLE
Unable to remove <lastmod/> Tag

### ISSUE THREAD

**Issue by bdong8boss** [TryGhost/gatsby-plugin-advanced-sitemap#83]
### Issue Summary

```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>https://documentation.elasticpath.com/sitemap-pages.xml</loc>
        <lastmod>2020-07-14T15:57:24.639Z</lastmod>
    </sitemap>
    <sitemap>
        <loc>/commerce-cloud/sitemap.xml</loc>
        <lastmod>2020-07-14T15:57:24.641Z</lastmod>
    </sitemap>
</sitemapindex>
```

We would like to exclude the <lastmod/> tag in the sitemap, but there isn't any configuration for that and we can't edit the XML file directly. 

### To Reproduce

1. yarn install the plugin package. 
2. add the plugin in gatsby-config.js
3. add the additional sitemap URL

### Technical details:

* Gatsby Version: 2.13.51
* Node Version: 13.8.0
* OS: MacOS 10.15
* gatsby-config.js:

**Comment by aileen** [comment]
Hey @bdong8boss 

There's currently no intention from our side to remove the `<lastmod>` tag or make it an optional value. Happy to check and merge PRs if you think this should be an option 😃

**Comment by bdong8boss** [comment]
thanks, I think we can close this one for now
