### ISSUE TITLE
`/` not listed when plugin used in default settings

### ISSUE THREAD

**Issue by aileen** [TryGhost/gatsby-plugin-advanced-sitemap#9]
### Issue Summary

When the plugin is used without further configuration, the home page `/` is not listed in `sitemap-pages.xml`

### To Reproduce

1. Use this plugin without any option e. g. with the [Gatsby Starter Ghost](https://github.com/TryGhost/gatsby-starter-ghost)
2. Ran `yarn serve`
3. See, how the home page is missing

**Comment by AkashRajpurohit** [comment]
I noticed the same thing when I used this plugin to generate the sitemap for my new website.

Earlier I was importing the plugin as
```
..
`gatsby-plugin-advanced-sitemap`
..
```

I have changed it to a different config to have different blocks for the different section of my site.
The new config is like this

```
...
{
    resolve: `gatsby-plugin-advanced-sitemap`,
    options: {
      query: `
      {
        allProjects: allSitePage(filter: {path: {regex: "/^/project/"}}) {
          edges {
            node {
              id
              slug: path
            }
          }
        }
        allTags: allSitePage(filter: {path: {regex: "/^/tag/"}}) {
          edges {
            node {
              id
              slug: path
            }
          }
        }
        allBlogs: allSitePage(filter: {path: {regex: "/^/blog/"}}) {
          edges {
            node {
              id
              slug: path
            }
          }
        }
        site {
          siteMetadata {
            siteUrl
          }
        }
      }`,
      mapping: {
        allProjects: {
          sitemap: `projects`,
        },
        allTags: {
          sitemap: `tags`,
        },
        allBlogs: {
          sitemap: `blogs`,
        },
      },
      exclude: [
        `/dev-404-page`,
        `/404`,
        `/404.html`,
        `/offline-plugin-app-shell-fallback`
      ],
      createLinkInHead: true,
      addUncaughtPages: true, // keep this true to add sitemap-pages where /about and / will be present
    }
  },
...
```

Now I have the `/` route as well in the `sitemap-pages.xml` file.

Have attached the screenshots below. Also, you can refer to the link directly [website sitemap](https://akashwho.codes/sitemap.xml)

![1](https://user-images.githubusercontent.com/30044630/71808393-b00a1d00-3093-11ea-8d0d-0652b14fd2c7.png)
![2](https://user-images.githubusercontent.com/30044630/71808394-b00a1d00-3093-11ea-8444-ad18ce094525.png)

Let me know if it helps. :)

**Comment by babgyy** [comment]
Thanks @AkashRajpurohit for the indications. I ended up doing something similar.
I had to update the plugin to the latest to make it work.
One problem with your solution in my setup : i only wanted one sitemap. 
So I ended up writing a query that matches no pages, in order to have all of my pages uncaught and gathered in a single sitemap

My config 

```
...
{
  resolve: `gatsby-plugin-advanced-sitemap`,
  options: {
    query: `
    {
      site {
        siteMetadata {
          siteUrl
        }
      }
    }`,
    exclude: [
      `/dev-404-page`,
      `/404`,
      `/404.html`,
      `/offline-plugin-app-shell-fallback`
    ],
    createLinkInHead: true,
    addUncaughtPages: true
  }
},
```

**Comment by muravitskiy** [comment]
Here is the problem: `getNodePath` returns an incorrect result for `/` node, that's why it is not included in the final sitemap.
